[pytest]

addopts = -v -s

testpaths = step_definitions

python_files = test_*.py

markers =
    smoke: Smoke suite
    regression: Regression suite
    sanity: Sanity suite
    checkout: Checkout tests
    login: Login tests